# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and Deploy Backend

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  AZURE_WEBAPP_PACKAGE_PATH: "./dist"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: Write secret to file
        run: |
          echo DATABASE_URL=$URL >> .env
        working-directory: ./advisor-backend
        shell: bash
        env:
          URL: ${{ secrets.DATABASE_URL }}

      - name: npm install, build, and test
        working-directory: ./advisor-backend
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Push Prisma migration to database
        working-directory: ./advisor-backend
        run: |
          npx prisma db push

      - name: Zip artifact for deployment
        run: zip ../backend.zip ./* -x node_modules -r
        working-directory: ./advisor-backend

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app-backend
          path: ./backend.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app-backend

      - name: unzip artifact for deployment
        run: unzip backend.zip

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "TABackend"
          slot-name: "Production"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_BACKEND }}
