name: Coverage report upload

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test frontend
    defaults:
      run:
        working-directory: ./advisor-frontend
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: "16.x"
    - name: npm install
        working-directory: ./advisor-frontend
        run: |
          npm install
    - name: Run tests and collect coverage
      working-directory: ./advisor-frontend
      run: |
          npm run coverage
    - name: Upload coverage reports to Codecov with GitHub Action
      working-directory: ./advisor-frontend
      uses: codecov/codecov-action@v3